name: Github Actios - Pull
run-name: Running - ${{ github.event_name }}
on:
  pull_request:
    branches:
      - development
    types:
      - opened
      - reopened
      - closed
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Comentário PULL REQUEST WORKFLOW"
