name: Github actions - Push Template Basic
run-name: Running - ${{ github.event_name }}
on:
  push:
    branches-ignore:
      - master
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Comentário do workflow PUSH"
#